Fix datetime csfix
hiqdev/hiapi-rcp-traf pull request #22
Opened 2020-10-05 11:40 UTC by bladeroot

2020-10-05 17:07 UTC, SilverFire requested changes

2020-10-05 17:07 UTC, SilverFire commented on src/collectors/AbstractCollector.php
> +    protected DateTimeImmutable $minTime;
Свойста, которые не объявлены в конструкторе опасно делать Not nullable. Попытка обратиться к ним до инициализаици приведёт к Fatal error.

Либо убедить что свойство точно-точно будет инициализировано, либо делаей его Nullable со значением по умолчанию

2020-10-06 07:38 UTC, SilverFire requested changes

2020-10-06 07:38 UTC, SilverFire commented on src/collectors/AbstractCollector.php
> +    protected ?RcpTrafTool $tool = null;
тут не вижу смысла в Nullable, это гарантируется конструктором

2020-11-05 10:33 UTC, hiqsol commented on src/collectors/AbstractCollector.php
> +    protected function renderConfig($rows, $format) : ?string
```suggestion
    protected function renderConfig($rows, $format) : string
```
тут точно строка

2020-11-05 10:33 UTC, hiqsol commented on src/collectors/AbstractCollector.php
> +    protected function buildLastTimeJoin() : ?string
```suggestion
    protected function buildLastTimeJoin() : string
```
тут тоже точно строка

2020-11-05 16:00 UTC, hiqsol commented on src/collectors/AbstractCollector.php
>          if (isset($time)) {
вместо всего ифа можно просто
```suggestion
        $time = $time ?? $default
```

2020-11-05 16:01 UTC, hiqsol commented on src/collectors/AbstractCollector.php
> +        return new DateTimeImmutable($default);
```suggestion
        return new DateTimeImmutable($time ?? $default);
```

вот так!

2020-11-05 16:01 UTC, hiqsol commented on src/collectors/AbstractCollector.php
>          if (isset($time)) {
не так

2020-11-05 16:44 UTC, hiqsol approved these changes

2020-11-05 16:45 UTC, merged