add collect usage for targets
hiqdev/hiapi-rcp-traf pull request #25
Opened 2021-06-24 10:38 UTC by bladeroot

2021-06-25 06:40 UTC, strorch approved these changes

2021-06-25 11:37 UTC, hiqsol requested changes
Выдвигай UNION ALL влево чтобы читалось

2021-06-25 11:37 UTC, hiqsol commented on src/collectors/ServerDuCollector.php
> +                    UNION ALL
```suggestion
                UNION ALL
```

2021-06-25 11:37 UTC, hiqsol commented on src/collectors/ServerDuCollector.php
> +                    UNION ALL
```suggestion
                UNION ALL
```

2021-06-25 11:37 UTC, hiqsol commented on src/collectors/ServerTrafCollector.php
> +                    UNION ALL
```suggestion
                UNION ALL
```

2021-06-25 11:37 UTC, hiqsol commented on src/collectors/ServerTrafCollector.php
> +                    UNION ALL
```suggestion
                UNION ALL
```

2021-06-29 11:04 UTC, hiqsol approved these changes

2021-06-29 11:05 UTC, merged